"""First Alembic Migration revision.

Application database schema will be created with::

   $ ./manage schema upgrade head

if this is the last revision. replace 'head' with `revision` number to force it.

About seeding data
~~~~~~~~~~~~~~~~~~

in manage.init_data() we do::

   admin = User(username=app.config['ADMIN_USERNAME'], email=app.config['ADMIN_EMAIL'], password=app.config['ADMIN_PASSWORD'])

`op.bulk_insert <http://alembic.readthedocs.org/en/latest/ops.html#alembic.operations.Operations.bulk_insert>`_
cannot be used directly because we want to encrypt password,

We may be able to use `alembic.context <http://alembic.readthedocs.org/en/latest/api.html#module-alembic.migration>`_
but `manager.command <http://flask-script.readthedocs.org/en/latest/#creating-and-running-commands>`_ might be a better option .

:seealso: http://alembic.readthedocs.org/en/latest/cookbook.html#conditional-migration-elements

Revision ID: 7b278e6e2b9
Revises: None
Create Date: 2014-06-17 22:50:32.481979

"""

# revision identifiers, used by Alembic.
revision = '7b278e6e2b9'
down_revision = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    """
    .. rubric:: Users Table

    In base blueprint we defined a :class:`~base.models.User`,
    which is used by `Flask-Login <https://flask-login.readthedocs.org/en/latest/>`_ to manage web sessions.

    Beware that the password column is encrypted.

    .. rubric:: Flaskr Entries Table

    This is for the first model of `Flaskr` blueprint:
    :class:`~flaskr.models.Entry`

    """
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('flaskr_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    """
    Drops application tables while preserving alembic's internal data,
    which is stored in same database.

    """
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flaskr_entries')
    op.drop_table('users')
    ### end Alembic commands ###
